version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      mynetwork:
        ipv4_address: 192.168.1.11
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    networks:
      mynetwork:
        ipv4_address: 192.168.1.12
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./bulk_data.json:/usr/share/elasticsearch/config/bulk_data.json
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]

volumes:
  mongodata:
  esdata:
    
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

